package cl.mp.rgp.ingreso.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Custodia implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Id")
	private java.lang.String id;

	public Custodia() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public Custodia(java.lang.String id) {
		this.id = id;
	}

}