package cl.mp.rgp.ingreso.model;

import cl.mp.rgp.ingreso.model.Denuncia;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DenunciaParteElectronico extends Denuncia
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	public DenunciaParteElectronico() {
	}

}