package cl.mp.rgp.ingreso.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DenunciaMigracion extends Denuncia implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public DenunciaMigracion() {
	}

}