package cl.mp.rgp.flagrancia.model;

/**
 * This class was automatically generated by the data modeler tool.
 */
 
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class Diligencia implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Id Diligencia")
	private java.lang.Integer idDiligencia;
	@org.kie.api.definition.type.Label(value = "Tipo")
	private java.lang.String tipo;
	@org.kie.api.definition.type.Label(value = "Descripcion")
	private java.lang.String descripcion;

	public Diligencia() {
	}

	public java.lang.Integer getIdDiligencia() {
		return this.idDiligencia;
	}

	public void setIdDiligencia(java.lang.Integer idDiligencia) {
		this.idDiligencia = idDiligencia;
	}

	public java.lang.String getTipo() {
		return this.tipo;
	}

	public void setTipo(java.lang.String tipo) {
		this.tipo = tipo;
	}

	public java.lang.String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(java.lang.String descripcion) {
		this.descripcion = descripcion;
	}

	public Diligencia(java.lang.Integer idDiligencia, java.lang.String tipo,
			java.lang.String descripcion) {
		this.idDiligencia = idDiligencia;
		this.tipo = tipo;
		this.descripcion = descripcion;
	}
	
	@Override
    public String toString() {
		ObjectMapper mapper = new ObjectMapper();
		String json = null;
		try {
			json = mapper.writeValueAsString(this);
		} catch (JsonProcessingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        return json;
    }

}
