package cl.mp.rgp.flagrancia.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.Date;

public class Procedimiento implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("ID Procedimiento")
	private java.lang.String idProcedimiento;

	@org.kie.api.definition.type.Label("Identificador de Folio")
	private Integer idFolio;

	@org.kie.api.definition.type.Label("Imputados")
	private java.util.List<cl.mp.rgp.common.model.ArquetipoPersona> imputados;

	@org.kie.api.definition.type.Label("Testigos")
	private java.util.List<cl.mp.rgp.common.model.ArquetipoPersona> testigos;

	@org.kie.api.definition.type.Label("Funcionarios")
	private java.util.List<cl.mp.rgp.common.model.ArquetipoPersona> funcionarios;

	@org.kie.api.definition.type.Label("Especies ")
	private java.util.List<cl.mp.rgp.common.model.Especie> especies;

	@org.kie.api.definition.type.Label("Diligencias")
	private java.util.List<cl.mp.rgp.flagrancia.model.Diligencia> diligencias;

	@org.kie.api.definition.type.Label("Antecedentes")
	private java.util.List<cl.mp.rgp.common.model.Documentacion> antecedentes;

	@org.kie.api.definition.type.Label("Delitos")
	private java.util.List<cl.mp.rgp.flagrancia.model.Delito> delitos;

	@org.kie.api.definition.type.Label("Hecho Delictual")
	private java.lang.Boolean hechoDelictual;

	@org.kie.api.definition.type.Label("Denunciantes ")
	private java.util.List<cl.mp.rgp.common.model.ArquetipoPersona> denunciantes;

	@org.kie.api.definition.type.Label("Victimas")
	private java.util.List<cl.mp.rgp.common.model.ArquetipoPersona> victimas;

	@org.kie.api.definition.type.Label("Inicio Turno Flagrancia")
	private java.lang.Boolean inicioTurnoFlagrancia;

	private java.lang.String idDenuncia;

	private java.lang.Boolean existenLesionados;

	private java.lang.Boolean existenFallecidos;

	private java.lang.Integer cantDetenidos;

	private java.lang.String alerta;

	private Date fechaIngreso;

	private java.lang.String nombreResponsable;

	private java.lang.Boolean esDirectaFlagrante;

	private java.lang.String codEstadoFolio;

	private java.lang.Boolean existenDetenidosPendiente;

	private java.lang.Integer cantDetenidosAcd;

	public Procedimiento() {
	}

	public java.util.List<cl.mp.rgp.common.model.ArquetipoPersona> getImputados() {
		return this.imputados;
	}

	public void setImputados(
			java.util.List<cl.mp.rgp.common.model.ArquetipoPersona> imputados) {
		this.imputados = imputados;
	}

	public java.util.List<cl.mp.rgp.common.model.ArquetipoPersona> getTestigos() {
		return this.testigos;
	}

	public void setTestigos(
			java.util.List<cl.mp.rgp.common.model.ArquetipoPersona> testigos) {
		this.testigos = testigos;
	}

	public java.util.List<cl.mp.rgp.common.model.ArquetipoPersona> getFuncionarios() {
		return this.funcionarios;
	}

	public void setFuncionarios(
			java.util.List<cl.mp.rgp.common.model.ArquetipoPersona> funcionarios) {
		this.funcionarios = funcionarios;
	}

	public java.util.List<cl.mp.rgp.common.model.Especie> getEspecies() {
		return this.especies;
	}

	public void setEspecies(
			java.util.List<cl.mp.rgp.common.model.Especie> especies) {
		this.especies = especies;
	}

	public java.util.List<cl.mp.rgp.flagrancia.model.Diligencia> getDiligencias() {
		return this.diligencias;
	}

	public void setDiligencias(
			java.util.List<cl.mp.rgp.flagrancia.model.Diligencia> diligencias) {
		this.diligencias = diligencias;
	}

	public java.util.List<cl.mp.rgp.common.model.Documentacion> getAntecedentes() {
		return this.antecedentes;
	}

	public void setAntecedentes(
			java.util.List<cl.mp.rgp.common.model.Documentacion> antecedentes) {
		this.antecedentes = antecedentes;
	}

	public java.util.List<cl.mp.rgp.flagrancia.model.Delito> getDelitos() {
		return this.delitos;
	}

	public void setDelitos(
			java.util.List<cl.mp.rgp.flagrancia.model.Delito> delitos) {
		this.delitos = delitos;
	}

	public java.lang.Boolean getHechoDelictual() {
		return this.hechoDelictual;
	}

	public void setHechoDelictual(java.lang.Boolean hechoDelictual) {
		this.hechoDelictual = hechoDelictual;
	}

	public java.util.List<cl.mp.rgp.common.model.ArquetipoPersona> getDenunciantes() {
		return this.denunciantes;
	}

	public void setDenunciantes(
			java.util.List<cl.mp.rgp.common.model.ArquetipoPersona> denunciantes) {
		this.denunciantes = denunciantes;
	}

	public java.util.List<cl.mp.rgp.common.model.ArquetipoPersona> getVictimas() {
		return this.victimas;
	}

	public void setVictimas(
			java.util.List<cl.mp.rgp.common.model.ArquetipoPersona> victimas) {
		this.victimas = victimas;
	}

	public java.lang.String getIdProcedimiento() {
		return this.idProcedimiento;
	}

	public void setIdProcedimiento(java.lang.String idProcedimiento) {
		this.idProcedimiento = idProcedimiento;
	}

	public Procedimiento(
			java.lang.Integer idFolio,
			java.util.List<cl.mp.rgp.common.model.ArquetipoPersona> imputados,
			java.util.List<cl.mp.rgp.common.model.ArquetipoPersona> testigos,
			java.util.List<cl.mp.rgp.common.model.ArquetipoPersona> funcionarios,
			java.util.List<cl.mp.rgp.common.model.Especie> especies,
			java.util.List<cl.mp.rgp.flagrancia.model.Diligencia> diligencias,
			java.util.List<cl.mp.rgp.common.model.Documentacion> antecedentes,
			java.util.List<cl.mp.rgp.flagrancia.model.Delito> delitos,
			java.lang.Boolean hechoDelictual,
			java.util.List<cl.mp.rgp.common.model.ArquetipoPersona> denunciantes,
			java.util.List<cl.mp.rgp.common.model.ArquetipoPersona> victimas,
			java.lang.String idProcedimiento) {
		this.idFolio = idFolio;
		this.imputados = imputados;
		this.testigos = testigos;
		this.funcionarios = funcionarios;
		this.especies = especies;
		this.diligencias = diligencias;
		this.antecedentes = antecedentes;
		this.delitos = delitos;
		this.hechoDelictual = hechoDelictual;
		this.denunciantes = denunciantes;
		this.victimas = victimas;
		this.idProcedimiento = idProcedimiento;
	}

	public java.lang.Integer getIdFolio() {
		return this.idFolio;
	}

	public void setIdFolio(java.lang.Integer idFolio) {
		this.idFolio = idFolio;
	}

	public java.lang.Boolean getInicioTurnoFlagrancia() {
		return this.inicioTurnoFlagrancia;
	}

	public void setInicioTurnoFlagrancia(java.lang.Boolean inicioTurnoFlagrancia) {
		this.inicioTurnoFlagrancia = inicioTurnoFlagrancia;
	}

	@Override
	public String toString() {
		ObjectMapper mapper = new ObjectMapper();
		String json = null;
		try {
			json = mapper.writeValueAsString(this);
		} catch (JsonProcessingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return json;
	}

	public java.lang.String getIdDenuncia() {
		return this.idDenuncia;
	}

	public void setIdDenuncia(java.lang.String idDenuncia) {
		this.idDenuncia = idDenuncia;
	}

	public java.lang.Boolean getExistenLesionados() {
		return this.existenLesionados;
	}

	public void setExistenLesionados(java.lang.Boolean existenLesionados) {
		this.existenLesionados = existenLesionados;
	}

	public java.lang.Boolean getExistenFallecidos() {
		return this.existenFallecidos;
	}

	public void setExistenFallecidos(java.lang.Boolean existenFallecidos) {
		this.existenFallecidos = existenFallecidos;
	}

	public java.lang.Integer getCantDetenidos() {
		return this.cantDetenidos;
	}

	public void setCantDetenidos(java.lang.Integer cantDetenidos) {
		this.cantDetenidos = cantDetenidos;
	}

	public java.lang.String getAlerta() {
		return this.alerta;
	}

	public void setAlerta(java.lang.String alerta) {
		this.alerta = alerta;
	}

	public java.lang.String getNombreResponsable() {
		return this.nombreResponsable;
	}

	public void setNombreResponsable(java.lang.String nombreResponsable) {
		this.nombreResponsable = nombreResponsable;
	}

	public java.util.Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(java.util.Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public java.lang.Boolean getEsDirectaFlagrante() {
		return this.esDirectaFlagrante;
	}

	public void setEsDirectaFlagrante(java.lang.Boolean esDirectaFlagrante) {
		this.esDirectaFlagrante = esDirectaFlagrante;
	}

	public java.lang.String getCodEstadoFolio() {
		return this.codEstadoFolio;
	}

	public void setCodEstadoFolio(java.lang.String codEstadoFolio) {
		this.codEstadoFolio = codEstadoFolio;
	}

	public java.lang.Boolean getExistenDetenidosPendiente() {
		return this.existenDetenidosPendiente;
	}

	public void setExistenDetenidosPendiente(
			java.lang.Boolean existenDetenidosPendiente) {
		this.existenDetenidosPendiente = existenDetenidosPendiente;
	}

	public java.lang.Integer getCantDetenidosAcd() {
		return this.cantDetenidosAcd;
	}

	public void setCantDetenidosAcd(java.lang.Integer cantDetenidosAcd) {
		this.cantDetenidosAcd = cantDetenidosAcd;
	}

	public Procedimiento(
			java.lang.String idProcedimiento,
			java.lang.Integer idFolio,
			java.util.List<cl.mp.rgp.common.model.ArquetipoPersona> imputados,
			java.util.List<cl.mp.rgp.common.model.ArquetipoPersona> testigos,
			java.util.List<cl.mp.rgp.common.model.ArquetipoPersona> funcionarios,
			java.util.List<cl.mp.rgp.common.model.Especie> especies,
			java.util.List<cl.mp.rgp.flagrancia.model.Diligencia> diligencias,
			java.util.List<cl.mp.rgp.common.model.Documentacion> antecedentes,
			java.util.List<cl.mp.rgp.flagrancia.model.Delito> delitos,
			java.lang.Boolean hechoDelictual,
			java.util.List<cl.mp.rgp.common.model.ArquetipoPersona> denunciantes,
			java.util.List<cl.mp.rgp.common.model.ArquetipoPersona> victimas,
			java.lang.Boolean inicioTurnoFlagrancia,
			java.lang.String idDenuncia, java.lang.Boolean existenLesionados,
			java.lang.Boolean existenFallecidos,
			java.lang.Integer cantDetenidos, java.lang.String alerta,
			java.util.Date fechaIngreso, java.lang.String nombreResponsable,
			java.lang.Boolean esDirectaFlagrante,
			java.lang.String codEstadoFolio,
			java.lang.Boolean existenDetenidosPendiente,
			java.lang.Integer cantDetenidosAcd) {
		this.idProcedimiento = idProcedimiento;
		this.idFolio = idFolio;
		this.imputados = imputados;
		this.testigos = testigos;
		this.funcionarios = funcionarios;
		this.especies = especies;
		this.diligencias = diligencias;
		this.antecedentes = antecedentes;
		this.delitos = delitos;
		this.hechoDelictual = hechoDelictual;
		this.denunciantes = denunciantes;
		this.victimas = victimas;
		this.inicioTurnoFlagrancia = inicioTurnoFlagrancia;
		this.idDenuncia = idDenuncia;
		this.existenLesionados = existenLesionados;
		this.existenFallecidos = existenFallecidos;
		this.cantDetenidos = cantDetenidos;
		this.alerta = alerta;
		this.fechaIngreso = fechaIngreso;
		this.nombreResponsable = nombreResponsable;
		this.esDirectaFlagrante = esDirectaFlagrante;
		this.codEstadoFolio = codEstadoFolio;
		this.existenDetenidosPendiente = existenDetenidosPendiente;
		this.cantDetenidosAcd = cantDetenidosAcd;
	}

}
