package cl.mp.rgp;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class testObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String id;
	private java.util.List<cl.mp.rgp.common.model.Relacion> relaciones;

	private java.lang.String plazo;

	public testObject() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.util.List<cl.mp.rgp.common.model.Relacion> getRelaciones() {
		return this.relaciones;
	}

	public void setRelaciones(
			java.util.List<cl.mp.rgp.common.model.Relacion> relaciones) {
		this.relaciones = relaciones;
	}

	public java.lang.String getPlazo() {
		return this.plazo;
	}

	public void setPlazo(java.lang.String plazo) {
		this.plazo = plazo;
	}

	public testObject(java.lang.String id,
			java.util.List<cl.mp.rgp.common.model.Relacion> relaciones,
			java.lang.String plazo) {
		this.id = id;
		this.relaciones = relaciones;
		this.plazo = plazo;
	}

}