package cl.mp.rgp.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AgruparSeparar implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String idAgrupacionSeparacion;
	private cl.mp.rgp.ingreso.model.Causa causaPrimaria;
	private java.util.List<cl.mp.rgp.ingreso.model.Causa> causasSecundarias;

	private java.lang.String tipo;

	public AgruparSeparar() {
	}

	public java.lang.String getIdAgrupacionSeparacion() {
		return this.idAgrupacionSeparacion;
	}

	public void setIdAgrupacionSeparacion(
			java.lang.String idAgrupacionSeparacion) {
		this.idAgrupacionSeparacion = idAgrupacionSeparacion;
	}

	public cl.mp.rgp.ingreso.model.Causa getCausaPrimaria() {
		return this.causaPrimaria;
	}

	public void setCausaPrimaria(cl.mp.rgp.ingreso.model.Causa causaPrimaria) {
		this.causaPrimaria = causaPrimaria;
	}

	public java.util.List<cl.mp.rgp.ingreso.model.Causa> getCausasSecundarias() {
		return this.causasSecundarias;
	}

	public void setCausasSecundarias(
			java.util.List<cl.mp.rgp.ingreso.model.Causa> causasSecundarias) {
		this.causasSecundarias = causasSecundarias;
	}

	public java.lang.String getTipo() {
		return this.tipo;
	}

	public void setTipo(java.lang.String tipo) {
		this.tipo = tipo;
	}

	public AgruparSeparar(java.lang.String idAgrupacionSeparacion,
			cl.mp.rgp.ingreso.model.Causa causaPrimaria,
			java.util.List<cl.mp.rgp.ingreso.model.Causa> causasSecundarias,
			java.lang.String tipo) {
		this.idAgrupacionSeparacion = idAgrupacionSeparacion;
		this.causaPrimaria = causaPrimaria;
		this.causasSecundarias = causasSecundarias;
		this.tipo = tipo;
	}

}