package cl.mp.rgp.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ObjetoCCD implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String anexo_solicitante;
	private java.lang.String cargo_solicitante;
	private java.lang.String correo_solicitante;
	private java.lang.String fiscalia_solicitante;
	private java.lang.String id_solicitante;
	private java.lang.String metadata;
	private java.lang.String nombreCatalogo;
	private java.lang.String nombre_solicitante;
	private java.lang.Boolean saveCDD;
	private java.lang.String telefono_solicitante;

	public ObjetoCCD() {
	}

	public java.lang.String getAnexo_solicitante() {
		return this.anexo_solicitante;
	}

	public void setAnexo_solicitante(java.lang.String anexo_solicitante) {
		this.anexo_solicitante = anexo_solicitante;
	}

	public java.lang.String getCargo_solicitante() {
		return this.cargo_solicitante;
	}

	public void setCargo_solicitante(java.lang.String cargo_solicitante) {
		this.cargo_solicitante = cargo_solicitante;
	}

	public java.lang.String getCorreo_solicitante() {
		return this.correo_solicitante;
	}

	public void setCorreo_solicitante(java.lang.String correo_solicitante) {
		this.correo_solicitante = correo_solicitante;
	}

	public java.lang.String getFiscalia_solicitante() {
		return this.fiscalia_solicitante;
	}

	public void setFiscalia_solicitante(java.lang.String fiscalia_solicitante) {
		this.fiscalia_solicitante = fiscalia_solicitante;
	}

	public java.lang.String getId_solicitante() {
		return this.id_solicitante;
	}

	public void setId_solicitante(java.lang.String id_solicitante) {
		this.id_solicitante = id_solicitante;
	}

	public java.lang.String getMetadata() {
		return this.metadata;
	}

	public void setMetadata(java.lang.String metadata) {
		this.metadata = metadata;
	}

	public java.lang.String getNombreCatalogo() {
		return this.nombreCatalogo;
	}

	public void setNombreCatalogo(java.lang.String nombreCatalogo) {
		this.nombreCatalogo = nombreCatalogo;
	}

	public java.lang.String getNombre_solicitante() {
		return this.nombre_solicitante;
	}

	public void setNombre_solicitante(java.lang.String nombre_solicitante) {
		this.nombre_solicitante = nombre_solicitante;
	}

	public java.lang.Boolean getSaveCDD() {
		return this.saveCDD;
	}

	public void setSaveCDD(java.lang.Boolean saveCDD) {
		this.saveCDD = saveCDD;
	}

	public java.lang.String getTelefono_solicitante() {
		return this.telefono_solicitante;
	}

	public void setTelefono_solicitante(java.lang.String telefono_solicitante) {
		this.telefono_solicitante = telefono_solicitante;
	}

	public ObjetoCCD(java.lang.String anexo_solicitante,
			java.lang.String cargo_solicitante,
			java.lang.String correo_solicitante,
			java.lang.String fiscalia_solicitante,
			java.lang.String id_solicitante, java.lang.String metadata,
			java.lang.String nombreCatalogo,
			java.lang.String nombre_solicitante, java.lang.Boolean saveCDD,
			java.lang.String telefono_solicitante) {
		this.anexo_solicitante = anexo_solicitante;
		this.cargo_solicitante = cargo_solicitante;
		this.correo_solicitante = correo_solicitante;
		this.fiscalia_solicitante = fiscalia_solicitante;
		this.id_solicitante = id_solicitante;
		this.metadata = metadata;
		this.nombreCatalogo = nombreCatalogo;
		this.nombre_solicitante = nombre_solicitante;
		this.saveCDD = saveCDD;
		this.telefono_solicitante = telefono_solicitante;
	}

}