package cl.mp.rgp.common;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class ObjetoGCD implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String object_store;
	private java.lang.String clase_documental;
	private java.lang.String titulo_documento;
	private java.lang.String contenido_documento;
	private java.lang.String mime_type;
	private java.lang.String object_id;
	private java.lang.String nombre_catalogo;
	private java.lang.String metadata;

	private java.lang.String plazo;

	private java.lang.String id_solicitud;

	public ObjetoGCD() {
	}

	public java.lang.String getObject_store() {
		return this.object_store;
	}

	public void setObject_store(java.lang.String object_store) {
		this.object_store = object_store;
	}

	public java.lang.String getClase_documental() {
		return this.clase_documental;
	}

	public void setClase_documental(java.lang.String clase_documental) {
		this.clase_documental = clase_documental;
	}

	public java.lang.String getTitulo_documento() {
		return this.titulo_documento;
	}

	public void setTitulo_documento(java.lang.String titulo_documento) {
		this.titulo_documento = titulo_documento;
	}

	public java.lang.String getContenido_documento() {
		return this.contenido_documento;
	}

	public void setContenido_documento(java.lang.String contenido_documento) {
		this.contenido_documento = contenido_documento;
	}

	public java.lang.String getMime_type() {
		return this.mime_type;
	}

	public void setMime_type(java.lang.String mime_type) {
		this.mime_type = mime_type;
	}

	public java.lang.String getObject_id() {
		return this.object_id;
	}

	public void setObject_id(java.lang.String object_id) {
		this.object_id = object_id;
	}

	public java.lang.String getNombre_catalogo() {
		return this.nombre_catalogo;
	}

	public void setNombre_catalogo(java.lang.String nombre_catalogo) {
		this.nombre_catalogo = nombre_catalogo;
	}

	public java.lang.String getMetadata() {
		return this.metadata;
	}

	public void setMetadata(java.lang.String metadata) {
		this.metadata = metadata;
	}

	public java.lang.String getPlazo() {
		return this.plazo;
	}

	public void setPlazo(java.lang.String plazo) {
		this.plazo = plazo;
	}

	public java.lang.String getId_solicitud() {
		return this.id_solicitud;
	}
	
	@Override
	public String toString() {
		ObjectMapper mapper = new ObjectMapper();
		String temp = this.getContenido_documento();
		this.setContenido_documento("no disponible");
		String json = null;
		try {
			json = mapper.writeValueAsString(this);
		} catch (JsonProcessingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		this.setContenido_documento(temp);
		return json;
	}

	public void setId_solicitud(java.lang.String id_solicitud) {
		this.id_solicitud = id_solicitud;
	}

	public ObjetoGCD(java.lang.String object_store,
			java.lang.String clase_documental,
			java.lang.String titulo_documento,
			java.lang.String contenido_documento, java.lang.String mime_type,
			java.lang.String object_id, java.lang.String nombre_catalogo,
			java.lang.String metadata, java.lang.String plazo,
			java.lang.String id_solicitud) {
		this.object_store = object_store;
		this.clase_documental = clase_documental;
		this.titulo_documento = titulo_documento;
		this.contenido_documento = contenido_documento;
		this.mime_type = mime_type;
		this.object_id = object_id;
		this.nombre_catalogo = nombre_catalogo;
		this.metadata = metadata;
		this.plazo = plazo;
		this.id_solicitud = id_solicitud;
	}

}