package cl.mp.rgp.common.model;

/**
 * This class was automatically generated by the data modeler tool.
 */
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class AgruparCausas implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String idMotivoAgrupacion;
	private java.lang.String comentario;
	private java.util.List<cl.mp.rgp.common.model.CausaLista> causas;

	public AgruparCausas() {
	}

	public java.lang.String getIdMotivoAgrupacion() {
		return this.idMotivoAgrupacion;
	}

	public void setIdMotivoAgrupacion(java.lang.String idMotivoAgrupacion) {
		this.idMotivoAgrupacion = idMotivoAgrupacion;
	}

	public java.lang.String getComentario() {
		return this.comentario;
	}

	public void setComentario(java.lang.String comentario) {
		this.comentario = comentario;
	}

	public java.util.List<cl.mp.rgp.common.model.CausaLista> getCausas() {
		return this.causas;
	}

	public void setCausas(
	    java.util.List<cl.mp.rgp.common.model.CausaLista> causas) {
		this.causas = causas;
	}

	public AgruparCausas(java.lang.String idMotivoAgrupacion,
			java.lang.String comentario, 
			java.util.List<cl.mp.rgp.common.model.CausaLista> causas) {
		this.idMotivoAgrupacion = idMotivoAgrupacion;
		this.comentario = comentario;
		this.causas = causas;
	}
	
	@Override
    public String toString() {
		ObjectMapper mapper = new ObjectMapper();
		String json = null;
		try {
			json = mapper.writeValueAsString(this);
		} catch (JsonProcessingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        return json;
    }

}