package cl.mp.rgp.common.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CausaMigracion implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String idCausa;
	private java.lang.String idDenuncia;
	private java.lang.String complejidad;

	public CausaMigracion() {
	}

	public java.lang.String getIdCausa() {
		return this.idCausa;
	}

	public void setIdCausa(java.lang.String idCausa) {
		this.idCausa = idCausa;
	}

	public java.lang.String getIdDenuncia() {
		return this.idDenuncia;
	}

	public void setIdDenuncia(java.lang.String idDenuncia) {
		this.idDenuncia = idDenuncia;
	}

	public java.lang.String getComplejidad() {
		return this.complejidad;
	}

	public void setComplejidad(java.lang.String complejidad) {
		this.complejidad = complejidad;
	}

	public CausaMigracion(java.lang.String idCausa,
			java.lang.String idDenuncia, java.lang.String complejidad) {
		this.idCausa = idCausa;
		this.idDenuncia = idDenuncia;
		this.complejidad = complejidad;
	}

}