package cl.mp.rgp.common.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class CausaLista implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String idCausa;
	private java.lang.String idCondicion;

	private java.lang.Boolean esPrincipal;

	public CausaLista() {
	}

	public java.lang.String getIdCausa() {
		return this.idCausa;
	}

	public void setIdCausa(java.lang.String idCausa) {
		this.idCausa = idCausa;
	}

	public java.lang.String getIdCondicion() {
		return this.idCondicion;
	}

	public void setIdCondicion(java.lang.String idCondicion) {
		this.idCondicion = idCondicion;
	}

	public java.lang.Boolean getEsPrincipal() {
		return this.esPrincipal;
	}

	public void setEsPrincipal(java.lang.Boolean esPrincipal) {
		this.esPrincipal = esPrincipal;
	}

	@Override
	public String toString() {
		ObjectMapper mapper = new ObjectMapper();
		String json = null;
		try {
			json = mapper.writeValueAsString(this);
		} catch (JsonProcessingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return json;
	}

	public CausaLista(java.lang.String idCausa, java.lang.String idCondicion,
			java.lang.Boolean esPrincipal) {
		this.idCausa = idCausa;
		this.idCondicion = idCondicion;
		this.esPrincipal = esPrincipal;
	}

}