package cl.mp.rgp.common.model;

/**
 * This class was automatically generated by the data modeler tool.
 */
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class Desestimar implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String idMotivo;
	private java.lang.String idTipoTermino;
	private java.lang.String comentario;

	public Desestimar() {
	}

	public java.lang.String getIdMotivo() {
		return this.idMotivo;
	}

	public void setIdMotivo(java.lang.String idMotivo) {
		this.idMotivo = idMotivo;
	}

	public java.lang.String getIdTipoTermino() {
		return this.idTipoTermino;
	}

	public void setIdTipoTermino(java.lang.String idTipoTermino) {
		this.idTipoTermino = idTipoTermino;
	}

	public java.lang.String getComentario() {
		return this.comentario;
	}

	public void setComentario(java.lang.String comentario) {
		this.comentario = comentario;
	}

	public Desestimar(java.lang.String idMotivo,
			java.lang.String idTipoTermino, java.lang.String comentario) {
		this.idMotivo = idMotivo;
		this.idTipoTermino = idTipoTermino;
		this.comentario = comentario;
	}
	
	@Override
    public String toString() {
		ObjectMapper mapper = new ObjectMapper();
		String json = null;
		try {
			json = mapper.writeValueAsString(this);
		} catch (JsonProcessingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        return json;
    }

}