package cl.mp.rgp.common.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class Documentacion implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String idDocumento;
	private java.lang.String descripcion;
	private java.lang.String tipo;

	@org.kie.api.definition.type.Label("id CDD al que pertenece el documento")
	private java.lang.Long idCDD;

	private java.lang.String version;

	private java.lang.String nombre;

	private java.lang.Boolean evidencia;

	private java.lang.String ubicacion;

	@org.kie.api.definition.type.Label("Indicación relativa a la disponibilidad para ser consultado (Disponible, No Disponible)")
	private java.lang.Boolean disponibilidad;

	private java.lang.String claseDocumental;

	private java.lang.String procedencia;

	private java.util.Date fechaCreacion;

	private java.util.Date fechaActualizacion;

	private java.util.Date fechaEliminacion;

	@org.kie.api.definition.type.Label(value = "Indicación relativa al acceso y disposición para consulta de los documentos. (Acceso Restringido / Acceso Total)")
	private java.lang.String nivelAcceso;

	public Documentacion() {
	}

	public java.lang.String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(java.lang.String descripcion) {
		this.descripcion = descripcion;
	}

	public java.lang.String getTipo() {
		return this.tipo;
	}

	public void setTipo(java.lang.String tipo) {
		this.tipo = tipo;
	}

	public java.lang.String getIdDocumento() {
		return this.idDocumento;
	}

	public void setIdDocumento(java.lang.String idDocumento) {
		this.idDocumento = idDocumento;
	}

	@Override
	public String toString() {
		ObjectMapper mapper = new ObjectMapper();
		String json = null;
		try {
			json = mapper.writeValueAsString(this);
		} catch (JsonProcessingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return json;
	}

	public java.lang.Long getIdCDD() {
		return this.idCDD;
	}

	public void setIdCDD(java.lang.Long idCDD) {
		this.idCDD = idCDD;
	}

	public java.lang.String getVersion() {
		return this.version;
	}

	public void setVersion(java.lang.String version) {
		this.version = version;
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public java.lang.Boolean getEvidencia() {
		return this.evidencia;
	}

	public void setEvidencia(java.lang.Boolean evidencia) {
		this.evidencia = evidencia;
	}

	public java.lang.String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(java.lang.String ubicacion) {
		this.ubicacion = ubicacion;
	}

	public java.lang.Boolean getDisponibilidad() {
		return this.disponibilidad;
	}

	public void setDisponibilidad(java.lang.Boolean disponibilidad) {
		this.disponibilidad = disponibilidad;
	}

	public java.lang.String getClaseDocumental() {
		return this.claseDocumental;
	}

	public void setClaseDocumental(java.lang.String claseDocumental) {
		this.claseDocumental = claseDocumental;
	}

	public java.lang.String getProcedencia() {
		return this.procedencia;
	}

	public void setProcedencia(java.lang.String procedencia) {
		this.procedencia = procedencia;
	}

	public java.util.Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(java.util.Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public java.util.Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(java.util.Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public java.util.Date getFechaEliminacion() {
		return this.fechaEliminacion;
	}

	public void setFechaEliminacion(java.util.Date fechaEliminacion) {
		this.fechaEliminacion = fechaEliminacion;
	}

	public java.lang.String getNivelAcceso() {
		return this.nivelAcceso;
	}

	public void setNivelAcceso(java.lang.String nivelAcceso) {
		this.nivelAcceso = nivelAcceso;
	}

	public Documentacion(java.lang.String idDocumento,
			java.lang.String descripcion, java.lang.String tipo,
			java.lang.Long idCDD, java.lang.String version,
			java.lang.String nombre, java.lang.Boolean evidencia,
			java.lang.String ubicacion, java.lang.Boolean disponibilidad,
			java.lang.String claseDocumental, java.lang.String procedencia,
			java.util.Date fechaCreacion, java.util.Date fechaActualizacion,
			java.util.Date fechaEliminacion, java.lang.String nivelAcceso) {
		this.idDocumento = idDocumento;
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.idCDD = idCDD;
		this.version = version;
		this.nombre = nombre;
		this.evidencia = evidencia;
		this.ubicacion = ubicacion;
		this.disponibilidad = disponibilidad;
		this.claseDocumental = claseDocumental;
		this.procedencia = procedencia;
		this.fechaCreacion = fechaCreacion;
		this.fechaActualizacion = fechaActualizacion;
		this.fechaEliminacion = fechaEliminacion;
		this.nivelAcceso = nivelAcceso;
	}

}
