package cl.mp.rgp.common.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class Especie implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String idEspecie;
	private java.lang.String tipo;
	private java.lang.String descripcion;
	private java.lang.String nue;

	private java.lang.Boolean esDinero;

	private java.lang.String familiaEspecie;

	public Especie() {
	}

	public java.lang.String getIdEspecie() {
		return this.idEspecie;
	}

	public void setIdEspecie(java.lang.String idEspecie) {
		this.idEspecie = idEspecie;
	}

	public java.lang.String getTipo() {
		return this.tipo;
	}

	public void setTipo(java.lang.String tipo) {
		this.tipo = tipo;
	}

	public java.lang.String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(java.lang.String descripcion) {
		this.descripcion = descripcion;
	}

	public java.lang.String getNue() {
		return this.nue;
	}

	public void setNue(java.lang.String nue) {
		this.nue = nue;
	}

	@Override
	public String toString() {
		ObjectMapper mapper = new ObjectMapper();
		String json = null;
		try {
			json = mapper.writeValueAsString(this);
		} catch (JsonProcessingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return json;
	}

	public java.lang.Boolean getEsDinero() {
		return this.esDinero;
	}

	public void setEsDinero(java.lang.Boolean esDinero) {
		this.esDinero = esDinero;
	}

	public java.lang.String getFamiliaEspecie() {
		return this.familiaEspecie;
	}

	public void setFamiliaEspecie(java.lang.String familiaEspecie) {
		this.familiaEspecie = familiaEspecie;
	}

	public Especie(java.lang.String idEspecie, java.lang.String tipo,
			java.lang.String descripcion, java.lang.String nue,
			java.lang.Boolean esDinero, java.lang.String familiaEspecie) {
		this.idEspecie = idEspecie;
		this.tipo = tipo;
		this.descripcion = descripcion;
		this.nue = nue;
		this.esDinero = esDinero;
		this.familiaEspecie = familiaEspecie;
	}

}