package cl.mp.rgp.common.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class Especies implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String idEspecie;
	private java.lang.String descripcion;
	private java.lang.String tipo;

	private java.lang.Boolean esDinero;

	public Especies() {
	}

	public java.lang.String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(java.lang.String descripcion) {
		this.descripcion = descripcion;
	}

	public java.lang.String getTipo() {
		return this.tipo;
	}

	public void setTipo(java.lang.String tipo) {
		this.tipo = tipo;
	}

	public java.lang.String getIdEspecie() {
		return this.idEspecie;
	}

	public void setIdEspecie(java.lang.String idEspecie) {
		this.idEspecie = idEspecie;
	}

	@Override
	public String toString() {
		ObjectMapper mapper = new ObjectMapper();
		String json = null;
		try {
			json = mapper.writeValueAsString(this);
		} catch (JsonProcessingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return json;
	}

	public java.lang.Boolean getEsDinero() {
		return this.esDinero;
	}

	public void setEsDinero(java.lang.Boolean esDinero) {
		this.esDinero = esDinero;
	}

	public Especies(java.lang.String idEspecie, java.lang.String descripcion,
			java.lang.String tipo, java.lang.Boolean esDinero) {
		this.idEspecie = idEspecie;
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.esDinero = esDinero;
	}

}
