package cl.mp.rgp.common.model;

/**
 * This class was automatically generated by the data modeler tool.
 */
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class ExternalReference implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean denunciaDuplicada;
	private java.lang.Boolean delitoFlagrante;
	private java.lang.Boolean denunciaFisico;
	private java.lang.Boolean denunciaParteElec;
	private java.lang.Boolean denunciaOficio;
	private java.lang.Boolean denunciaNueva;
	private java.lang.Boolean denunciaFlagrancia;
	private java.lang.Boolean esDenuncia;
	private java.lang.Boolean recibidoPjud;
	private cl.mp.rgp.ingreso.model.Denuncia denunciaPrincipal;
	private cl.mp.rgp.ingreso.model.Causa causaPrincipal;
	private java.util.List<cl.mp.rgp.ingreso.model.Causa> causasAuxiliares;
	private java.util.List<cl.mp.rgp.ingreso.model.Denuncia> denunciasAuxiliares;

	public ExternalReference() {
	}

	public java.lang.Boolean getDenunciaDuplicada() {
		return this.denunciaDuplicada;
	}

	public void setDenunciaDuplicada(java.lang.Boolean denunciaDuplicada) {
		this.denunciaDuplicada = denunciaDuplicada;
	}

	public java.lang.Boolean getDelitoFlagrante() {
		return this.delitoFlagrante;
	}

	public void setDelitoFlagrante(java.lang.Boolean delitoFlagrante) {
		this.delitoFlagrante = delitoFlagrante;
	}

	public java.lang.Boolean getDenunciaFisico() {
		return this.denunciaFisico;
	}

	public void setDenunciaFisico(java.lang.Boolean denunciaFisico) {
		this.denunciaFisico = denunciaFisico;
	}

	public java.lang.Boolean getDenunciaParteElec() {
		return this.denunciaParteElec;
	}

	public void setDenunciaParteElec(java.lang.Boolean denunciaParteElec) {
		this.denunciaParteElec = denunciaParteElec;
	}

	public java.lang.Boolean getDenunciaOficio() {
		return this.denunciaOficio;
	}

	public void setDenunciaOficio(java.lang.Boolean denunciaOficio) {
		this.denunciaOficio = denunciaOficio;
	}

	public java.lang.Boolean getDenunciaNueva() {
		return this.denunciaNueva;
	}

	public void setDenunciaNueva(java.lang.Boolean denunciaNueva) {
		this.denunciaNueva = denunciaNueva;
	}

	public java.lang.Boolean getDenunciaFlagrancia() {
		return this.denunciaFlagrancia;
	}

	public void setDenunciaFlagrancia(java.lang.Boolean denunciaFlagrancia) {
		this.denunciaFlagrancia = denunciaFlagrancia;
	}

	public java.lang.Boolean getEsDenuncia() {
		return this.esDenuncia;
	}

	public void setEsDenuncia(java.lang.Boolean esDenuncia) {
		this.esDenuncia = esDenuncia;
	}

	public java.lang.Boolean getRecibidoPjud() {
		return this.recibidoPjud;
	}

	public void setRecibidoPjud(java.lang.Boolean recibidoPjud) {
		this.recibidoPjud = recibidoPjud;
	}

	public cl.mp.rgp.ingreso.model.Denuncia getDenunciaPrincipal() {
		return this.denunciaPrincipal;
	}

	public void setDenunciaPrincipal(
			cl.mp.rgp.ingreso.model.Denuncia denunciaPrincipal) {
		this.denunciaPrincipal = denunciaPrincipal;
	}

	public cl.mp.rgp.ingreso.model.Causa getCausaPrincipal() {
		return this.causaPrincipal;
	}

	public void setCausaPrincipal(cl.mp.rgp.ingreso.model.Causa causaPrincipal) {
		this.causaPrincipal = causaPrincipal;
	}

	public java.util.List<cl.mp.rgp.ingreso.model.Causa> getCausasAuxiliares() {
		return this.causasAuxiliares;
	}

	public void setCausasAuxiliares(
			java.util.List<cl.mp.rgp.ingreso.model.Causa> causasAuxiliares) {
		this.causasAuxiliares = causasAuxiliares;
	}

	public java.util.List<cl.mp.rgp.ingreso.model.Denuncia> getDenunciasAuxiliares() {
		return this.denunciasAuxiliares;
	}

	public void setDenunciasAuxiliares(
			java.util.List<cl.mp.rgp.ingreso.model.Denuncia> denunciasAuxiliares) {
		this.denunciasAuxiliares = denunciasAuxiliares;
	}

	public ExternalReference(java.lang.Boolean denunciaDuplicada,
			java.lang.Boolean delitoFlagrante,
			java.lang.Boolean denunciaFisico,
			java.lang.Boolean denunciaParteElec,
			java.lang.Boolean denunciaOficio, java.lang.Boolean denunciaNueva,
			java.lang.Boolean denunciaFlagrancia, java.lang.Boolean esDenuncia,
			java.lang.Boolean recibidoPjud,
			cl.mp.rgp.ingreso.model.Denuncia denunciaPrincipal,
			cl.mp.rgp.ingreso.model.Causa causaPrincipal,
			java.util.List<cl.mp.rgp.ingreso.model.Causa> causasAuxiliares,
			java.util.List<cl.mp.rgp.ingreso.model.Denuncia> denunciasAuxiliares) {
		this.denunciaDuplicada = denunciaDuplicada;
		this.delitoFlagrante = delitoFlagrante;
		this.denunciaFisico = denunciaFisico;
		this.denunciaParteElec = denunciaParteElec;
		this.denunciaOficio = denunciaOficio;
		this.denunciaNueva = denunciaNueva;
		this.denunciaFlagrancia = denunciaFlagrancia;
		this.esDenuncia = esDenuncia;
		this.recibidoPjud = recibidoPjud;
		this.denunciaPrincipal = denunciaPrincipal;
		this.causaPrincipal = causaPrincipal;
		this.causasAuxiliares = causasAuxiliares;
		this.denunciasAuxiliares = denunciasAuxiliares;
	}
	
	@Override
    public String toString() {
		ObjectMapper mapper = new ObjectMapper();
		String json = null;
		try {
			json = mapper.writeValueAsString(this);
		} catch (JsonProcessingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        return json;
    }

}