package cl.mp.rgp.common.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InfoDm implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String abreviado;
	private java.lang.String ap;
	private java.lang.Integer cantidadIncumplimientos;
	private java.lang.String delito;
	private java.lang.String dnp;
	private java.lang.String duplicidad;
	private java.lang.String estadoCausa;
	private java.lang.String fiscalia;
	private java.lang.String marca;
	private java.lang.String plazoPrescripcion;
	private java.lang.String procedencia;
	private java.lang.String region;
	private java.lang.String rol;
	private java.lang.String scp;
	private java.lang.String sd;
	private java.lang.String tipoDelito;
	private java.lang.String tipoDocumento;
	private java.lang.String tipoNotificacion;
	private java.lang.String tipoSalidaDefinitiva;
	private java.lang.String tipoSentencia;
	private java.lang.String tipoTermino;
	private java.lang.String tipoEspecie;
	private java.lang.String respuestaPrincipal;
	private java.lang.String respuestaSecundaria;

	public InfoDm() {
	}

	public java.lang.String getAbreviado() {
		return this.abreviado;
	}

	public void setAbreviado(java.lang.String abreviado) {
		this.abreviado = abreviado;
	}

	public java.lang.String getAp() {
		return this.ap;
	}

	public void setAp(java.lang.String ap) {
		this.ap = ap;
	}

	public java.lang.Integer getCantidadIncumplimientos() {
		return this.cantidadIncumplimientos;
	}

	public void setCantidadIncumplimientos(
			java.lang.Integer cantidadIncumplimientos) {
		this.cantidadIncumplimientos = cantidadIncumplimientos;
	}

	public java.lang.String getDelito() {
		return this.delito;
	}

	public void setDelito(java.lang.String delito) {
		this.delito = delito;
	}

	public java.lang.String getDnp() {
		return this.dnp;
	}

	public void setDnp(java.lang.String dnp) {
		this.dnp = dnp;
	}

	public java.lang.String getDuplicidad() {
		return this.duplicidad;
	}

	public void setDuplicidad(java.lang.String duplicidad) {
		this.duplicidad = duplicidad;
	}

	public java.lang.String getEstadoCausa() {
		return this.estadoCausa;
	}

	public void setEstadoCausa(java.lang.String estadoCausa) {
		this.estadoCausa = estadoCausa;
	}

	public java.lang.String getFiscalia() {
		return this.fiscalia;
	}

	public void setFiscalia(java.lang.String fiscalia) {
		this.fiscalia = fiscalia;
	}

	public java.lang.String getMarca() {
		return this.marca;
	}

	public void setMarca(java.lang.String marca) {
		this.marca = marca;
	}

	public java.lang.String getPlazoPrescripcion() {
		return this.plazoPrescripcion;
	}

	public void setPlazoPrescripcion(java.lang.String plazoPrescripcion) {
		this.plazoPrescripcion = plazoPrescripcion;
	}

	public java.lang.String getProcedencia() {
		return this.procedencia;
	}

	public void setProcedencia(java.lang.String procedencia) {
		this.procedencia = procedencia;
	}

	public java.lang.String getRegion() {
		return this.region;
	}

	public void setRegion(java.lang.String region) {
		this.region = region;
	}

	public java.lang.String getRol() {
		return this.rol;
	}

	public void setRol(java.lang.String rol) {
		this.rol = rol;
	}

	public java.lang.String getScp() {
		return this.scp;
	}

	public void setScp(java.lang.String scp) {
		this.scp = scp;
	}

	public java.lang.String getSd() {
		return this.sd;
	}

	public void setSd(java.lang.String sd) {
		this.sd = sd;
	}

	public java.lang.String getTipoDelito() {
		return this.tipoDelito;
	}

	public void setTipoDelito(java.lang.String tipoDelito) {
		this.tipoDelito = tipoDelito;
	}

	public java.lang.String getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(java.lang.String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public java.lang.String getTipoNotificacion() {
		return this.tipoNotificacion;
	}

	public void setTipoNotificacion(java.lang.String tipoNotificacion) {
		this.tipoNotificacion = tipoNotificacion;
	}

	public java.lang.String getTipoSalidaDefinitiva() {
		return this.tipoSalidaDefinitiva;
	}

	public void setTipoSalidaDefinitiva(java.lang.String tipoSalidaDefinitiva) {
		this.tipoSalidaDefinitiva = tipoSalidaDefinitiva;
	}

	public java.lang.String getTipoSentencia() {
		return this.tipoSentencia;
	}

	public void setTipoSentencia(java.lang.String tipoSentencia) {
		this.tipoSentencia = tipoSentencia;
	}

	public java.lang.String getTipoTermino() {
		return this.tipoTermino;
	}

	public void setTipoTermino(java.lang.String tipoTermino) {
		this.tipoTermino = tipoTermino;
	}

	public java.lang.String getTipoEspecie() {
		return this.tipoEspecie;
	}

	public void setTipoEspecie(java.lang.String tipoEspecie) {
		this.tipoEspecie = tipoEspecie;
	}

	public java.lang.String getRespuestaPrincipal() {
		return this.respuestaPrincipal;
	}

	public void setRespuestaPrincipal(java.lang.String respuestaPrincipal) {
		this.respuestaPrincipal = respuestaPrincipal;
	}

	public java.lang.String getRespuestaSecundaria() {
		return this.respuestaSecundaria;
	}

	public void setRespuestaSecundaria(java.lang.String respuestaSecundaria) {
		this.respuestaSecundaria = respuestaSecundaria;
	}

	public InfoDm(java.lang.String abreviado, java.lang.String ap,
			java.lang.Integer cantidadIncumplimientos, java.lang.String delito,
			java.lang.String dnp, java.lang.String duplicidad,
			java.lang.String estadoCausa, java.lang.String fiscalia,
			java.lang.String marca, java.lang.String plazoPrescripcion,
			java.lang.String procedencia, java.lang.String region,
			java.lang.String rol, java.lang.String scp, java.lang.String sd,
			java.lang.String tipoDelito, java.lang.String tipoDocumento,
			java.lang.String tipoNotificacion,
			java.lang.String tipoSalidaDefinitiva,
			java.lang.String tipoSentencia, java.lang.String tipoTermino,
			java.lang.String tipoEspecie, java.lang.String respuestaPrincipal,
			java.lang.String respuestaSecundaria) {
		this.abreviado = abreviado;
		this.ap = ap;
		this.cantidadIncumplimientos = cantidadIncumplimientos;
		this.delito = delito;
		this.dnp = dnp;
		this.duplicidad = duplicidad;
		this.estadoCausa = estadoCausa;
		this.fiscalia = fiscalia;
		this.marca = marca;
		this.plazoPrescripcion = plazoPrescripcion;
		this.procedencia = procedencia;
		this.region = region;
		this.rol = rol;
		this.scp = scp;
		this.sd = sd;
		this.tipoDelito = tipoDelito;
		this.tipoDocumento = tipoDocumento;
		this.tipoNotificacion = tipoNotificacion;
		this.tipoSalidaDefinitiva = tipoSalidaDefinitiva;
		this.tipoSentencia = tipoSentencia;
		this.tipoTermino = tipoTermino;
		this.tipoEspecie = tipoEspecie;
		this.respuestaPrincipal = respuestaPrincipal;
		this.respuestaSecundaria = respuestaSecundaria;
	}

}