package cl.mp.rgp.common.model;

/**
 * This class was automatically generated by the data modeler tool.
 */
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class Preclasificacion implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private cl.mp.rgp.common.model.SeguirLineaInvestigativa seguirlinea;
	private cl.mp.rgp.common.model.Desestimar desestimar;
	private cl.mp.rgp.common.model.AgruparCausas agruparCausa;
	private cl.mp.rgp.common.model.Transferir transferir;

	public Preclasificacion() {
	}

	public cl.mp.rgp.common.model.SeguirLineaInvestigativa getSeguirlinea() {
		return this.seguirlinea;
	}

	public void setSeguirlinea(
			cl.mp.rgp.common.model.SeguirLineaInvestigativa seguirlinea) {
		this.seguirlinea = seguirlinea;
	}

	public cl.mp.rgp.common.model.Desestimar getDesestimar() {
		return this.desestimar;
	}

	public void setDesestimar(cl.mp.rgp.common.model.Desestimar desestimar) {
		this.desestimar = desestimar;
	}

	public cl.mp.rgp.common.model.AgruparCausas getAgruparCausa() {
		return this.agruparCausa;
	}

	public void setAgruparCausa(
			cl.mp.rgp.common.model.AgruparCausas agruparCausa) {
		this.agruparCausa = agruparCausa;
	}

	public cl.mp.rgp.common.model.Transferir getTransferir() {
		return this.transferir;
	}

	public void setTransferir(cl.mp.rgp.common.model.Transferir transferir) {
		this.transferir = transferir;
	}

	public Preclasificacion(
			cl.mp.rgp.common.model.SeguirLineaInvestigativa seguirlinea,
			cl.mp.rgp.common.model.Desestimar desestimar,
			cl.mp.rgp.common.model.AgruparCausas agruparCausa,
			cl.mp.rgp.common.model.Transferir transferir) {
		this.seguirlinea = seguirlinea;
		this.desestimar = desestimar;
		this.agruparCausa = agruparCausa;
		this.transferir = transferir;
	}
	
	@Override
    public String toString() {
		ObjectMapper mapper = new ObjectMapper();
		String json = null;
		try {
			json = mapper.writeValueAsString(this);
		} catch (JsonProcessingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        return json;
    }

}