package cl.mp.rgp.common.model;

/**
 * This class was automatically generated by the data modeler tool.
 */
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class SeguirLineaInvestigativa implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String idComplejidad;
	private java.lang.String idEspecialidad;
	private java.lang.String comentario;

	private java.lang.String idFiscalAsignado;

	public SeguirLineaInvestigativa() {
	}

	public java.lang.String getIdComplejidad() {
		return this.idComplejidad;
	}

	public void setIdComplejidad(java.lang.String idComplejidad) {
		this.idComplejidad = idComplejidad;
	}

	public java.lang.String getIdEspecialidad() {
		return this.idEspecialidad;
	}

	public void setIdEspecialidad(java.lang.String idEspecialidad) {
		this.idEspecialidad = idEspecialidad;
	}

	public java.lang.String getComentario() {
		return this.comentario;
	}

	public void setComentario(java.lang.String comentario) {
		this.comentario = comentario;
	}

	public java.lang.String getIdFiscalAsignado() {
		return this.idFiscalAsignado;
	}

	public void setIdFiscalAsignado(java.lang.String idFiscalAsignado) {
		this.idFiscalAsignado = idFiscalAsignado;
	}

	public SeguirLineaInvestigativa(java.lang.String idComplejidad,
			java.lang.String idEspecialidad, java.lang.String comentario,
			java.lang.String idFiscalAsignado) {
		this.idComplejidad = idComplejidad;
		this.idEspecialidad = idEspecialidad;
		this.comentario = comentario;
		this.idFiscalAsignado = idFiscalAsignado;
	}
	
	@Override
    public String toString() {
		ObjectMapper mapper = new ObjectMapper();
		String json = null;
		try {
			json = mapper.writeValueAsString(this);
		} catch (JsonProcessingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        return json;
    }

}