package cl.mp.rgp.common.model;

import org.kie.api.remote.Remotable;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Solicitud implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String id;
	private java.lang.String nombre;
	private java.lang.String tipo;
	private java.lang.String subTipo;

	private java.lang.String idResponsableMaterializar;

	private java.lang.String idInstitucionEjecutora;

	private java.util.Date plazoSolicitud;

	private java.util.Date fechaHoraSolicitud;

	private java.lang.Boolean materializarSolicitud;

	private java.lang.Boolean revisarSolicitud;

	private java.lang.String tipoDiligencia;

	private java.lang.Boolean requiereApoyo;

	private java.util.List<cl.mp.rgp.flagrancia.model.Delito> delitos;

	private java.lang.String plazo;

	private java.lang.String resolucion;

	private java.lang.Boolean primerVencimiento;

	private java.lang.Integer plazoAutomaticoDias;

	private java.lang.String nombreInstitucionEjecutora;

	private java.lang.String nombreResponsableMaterializar;

	private java.lang.Integer plazoDias;

	private java.lang.String token;

	public Solicitud() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public java.lang.String getTipo() {
		return this.tipo;
	}

	public void setTipo(java.lang.String tipo) {
		this.tipo = tipo;
	}

	public java.lang.String getSubTipo() {
		return this.subTipo;
	}

	public void setSubTipo(java.lang.String subTipo) {
		this.subTipo = subTipo;
	}

	public java.lang.String getIdResponsableMaterializar() {
		return this.idResponsableMaterializar;
	}

	public void setIdResponsableMaterializar(
			java.lang.String idResponsableMaterializar) {
		this.idResponsableMaterializar = idResponsableMaterializar;
	}

	public java.lang.String getIdInstitucionEjecutora() {
		return this.idInstitucionEjecutora;
	}

	public void setIdInstitucionEjecutora(
			java.lang.String idInstitucionEjecutora) {
		this.idInstitucionEjecutora = idInstitucionEjecutora;
	}

	public java.util.Date getPlazoSolicitud() {
		return this.plazoSolicitud;
	}

	public void setPlazoSolicitud(java.util.Date plazoSolicitud) {
		this.plazoSolicitud = plazoSolicitud;
	}

	public java.util.Date getFechaHoraSolicitud() {
		return this.fechaHoraSolicitud;
	}

	public void setFechaHoraSolicitud(java.util.Date fechaHoraSolicitud) {
		this.fechaHoraSolicitud = fechaHoraSolicitud;
	}

	public java.lang.Boolean getMaterializarSolicitud() {
		return this.materializarSolicitud;
	}

	public void setMaterializarSolicitud(java.lang.Boolean materializarSolicitud) {
		this.materializarSolicitud = materializarSolicitud;
	}

	public java.lang.Boolean getRevisarSolicitud() {
		return this.revisarSolicitud;
	}

	public void setRevisarSolicitud(java.lang.Boolean revisarSolicitud) {
		this.revisarSolicitud = revisarSolicitud;
	}

	public java.lang.String getTipoDiligencia() {
		return this.tipoDiligencia;
	}

	public void setTipoDiligencia(java.lang.String tipoDiligencia) {
		this.tipoDiligencia = tipoDiligencia;
	}

	public java.lang.Boolean getRequiereApoyo() {
		return this.requiereApoyo;
	}

	public void setRequiereApoyo(java.lang.Boolean requiereApoyo) {
		this.requiereApoyo = requiereApoyo;
	}

	public java.util.List<cl.mp.rgp.flagrancia.model.Delito> getDelitos() {
		return this.delitos;
	}

	public void setDelitos(
			java.util.List<cl.mp.rgp.flagrancia.model.Delito> delitos) {
		this.delitos = delitos;
	}

	@Override
	public String toString() {
		ObjectMapper mapper = new ObjectMapper();
		String tempToken = this.getToken();
		this.setToken("empty");
		String json = null;
		try {
			json = mapper.writeValueAsString(this);
		} catch (JsonProcessingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		this.setToken(tempToken);
		return json;
	}

	public java.lang.String getPlazo() {
		return this.plazo;
	}

	public void setPlazo(java.lang.String plazo) {
		this.plazo = plazo;
	}

	public java.lang.String getResolucion() {
		return this.resolucion;
	}

	public void setResolucion(java.lang.String resolucion) {
		this.resolucion = resolucion;
	}

	public java.lang.Boolean getPrimerVencimiento() {
		return this.primerVencimiento;
	}

	public void setPrimerVencimiento(java.lang.Boolean primerVencimiento) {
		this.primerVencimiento = primerVencimiento;
	}

	public java.lang.Integer getPlazoAutomaticoDias() {
		return this.plazoAutomaticoDias;
	}

	public void setPlazoAutomaticoDias(java.lang.Integer plazoAutomaticoDias) {
		this.plazoAutomaticoDias = plazoAutomaticoDias;
	}

	public java.lang.String getNombreInstitucionEjecutora() {
		return this.nombreInstitucionEjecutora;
	}

	public void setNombreInstitucionEjecutora(
			java.lang.String nombreInstitucionEjecutora) {
		this.nombreInstitucionEjecutora = nombreInstitucionEjecutora;
	}

	public java.lang.String getNombreResponsableMaterializar() {
		return this.nombreResponsableMaterializar;
	}

	public void setNombreResponsableMaterializar(
			java.lang.String nombreResponsableMaterializar) {
		this.nombreResponsableMaterializar = nombreResponsableMaterializar;
	}

	public java.lang.Integer getPlazoDias() {
		return this.plazoDias;
	}

	public void setPlazoDias(java.lang.Integer plazoDias) {
		this.plazoDias = plazoDias;
	}

	public java.lang.String getToken() {
		return this.token;
	}

	public void setToken(java.lang.String token) {
		this.token = token;
	}

	public Solicitud(java.lang.String id, java.lang.String nombre,
			java.lang.String tipo, java.lang.String subTipo,
			java.lang.String idResponsableMaterializar,
			java.lang.String idInstitucionEjecutora,
			java.util.Date plazoSolicitud, java.util.Date fechaHoraSolicitud,
			java.lang.Boolean materializarSolicitud,
			java.lang.Boolean revisarSolicitud,
			java.lang.String tipoDiligencia, java.lang.Boolean requiereApoyo,
			java.util.List<cl.mp.rgp.flagrancia.model.Delito> delitos,
			java.lang.String plazo, java.lang.String resolucion,
			java.lang.Boolean primerVencimiento,
			java.lang.Integer plazoAutomaticoDias,
			java.lang.String nombreInstitucionEjecutora,
			java.lang.String nombreResponsableMaterializar,
			java.lang.Integer plazoDias, java.lang.String token) {
		this.id = id;
		this.nombre = nombre;
		this.tipo = tipo;
		this.subTipo = subTipo;
		this.idResponsableMaterializar = idResponsableMaterializar;
		this.idInstitucionEjecutora = idInstitucionEjecutora;
		this.plazoSolicitud = plazoSolicitud;
		this.fechaHoraSolicitud = fechaHoraSolicitud;
		this.materializarSolicitud = materializarSolicitud;
		this.revisarSolicitud = revisarSolicitud;
		this.tipoDiligencia = tipoDiligencia;
		this.requiereApoyo = requiereApoyo;
		this.delitos = delitos;
		this.plazo = plazo;
		this.resolucion = resolucion;
		this.primerVencimiento = primerVencimiento;
		this.plazoAutomaticoDias = plazoAutomaticoDias;
		this.nombreInstitucionEjecutora = nombreInstitucionEjecutora;
		this.nombreResponsableMaterializar = nombreResponsableMaterializar;
		this.plazoDias = plazoDias;
		this.token = token;
	}

}