package cl.mp.rgp.common.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TerminoMetadata implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private cl.mp.rgp.ingreso.model.Causa causa;
	private cl.mp.rgp.common.model.PerfilamientoUsuarios usuario;
	private java.lang.String tipoTermino;
	private java.lang.String subTipoTermino;
	private java.lang.String motivoTermino;
	private java.lang.String ambiente;
	private java.lang.String token;

	public TerminoMetadata() {
	}

	public cl.mp.rgp.ingreso.model.Causa getCausa() {
		return this.causa;
	}

	public void setCausa(cl.mp.rgp.ingreso.model.Causa causa) {
		this.causa = causa;
	}

	public cl.mp.rgp.common.model.PerfilamientoUsuarios getUsuario() {
		return this.usuario;
	}

	public void setUsuario(cl.mp.rgp.common.model.PerfilamientoUsuarios usuario) {
		this.usuario = usuario;
	}

	public java.lang.String getTipoTermino() {
		return this.tipoTermino;
	}

	public void setTipoTermino(java.lang.String tipoTermino) {
		this.tipoTermino = tipoTermino;
	}

	public java.lang.String getSubTipoTermino() {
		return this.subTipoTermino;
	}

	public void setSubTipoTermino(java.lang.String subTipoTermino) {
		this.subTipoTermino = subTipoTermino;
	}

	public java.lang.String getMotivoTermino() {
		return this.motivoTermino;
	}

	public void setMotivoTermino(java.lang.String motivoTermino) {
		this.motivoTermino = motivoTermino;
	}

	public java.lang.String getAmbiente() {
		return this.ambiente;
	}

	public void setAmbiente(java.lang.String ambiente) {
		this.ambiente = ambiente;
	}

	public java.lang.String getToken() {
		return this.token;
	}

	public void setToken(java.lang.String token) {
		this.token = token;
	}

	public TerminoMetadata(cl.mp.rgp.ingreso.model.Causa causa,
			cl.mp.rgp.common.model.PerfilamientoUsuarios usuario,
			java.lang.String tipoTermino, java.lang.String subTipoTermino,
			java.lang.String motivoTermino, java.lang.String ambiente,
			java.lang.String token) {
		this.causa = causa;
		this.usuario = usuario;
		this.tipoTermino = tipoTermino;
		this.subTipoTermino = subTipoTermino;
		this.motivoTermino = motivoTermino;
		this.ambiente = ambiente;
		this.token = token;
	}

}