package cl.mp.rgp.common.model;

/**
 * This class was automatically generated by the data modeler tool.
 */
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class ValidacionesPamList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<cl.mp.rgp.common.model.ValidacionesPam> validacionesPam;

	@org.kie.api.definition.type.Label(value = "Activar (solo para funcionalidad de reglas)")
	private java.lang.Boolean activar;

	public ValidacionesPamList() {
	}

	public java.util.List<cl.mp.rgp.common.model.ValidacionesPam> getValidacionesPam() {
		return this.validacionesPam;
	}

	public void setValidacionesPam(
			java.util.List<cl.mp.rgp.common.model.ValidacionesPam> validacionesPam) {
		this.validacionesPam = validacionesPam;
	}

	public void addItem(cl.mp.rgp.common.model.ValidacionesPam valor) {
		validacionesPam.add(valor);
	}

	public java.lang.Boolean getActivar() {
		return this.activar;
	}

	public void setActivar(java.lang.Boolean activar) {
		this.activar = activar;
	}

	public ValidacionesPamList(
			java.util.List<cl.mp.rgp.common.model.ValidacionesPam> validacionesPam,
			java.lang.Boolean activar) {
		this.validacionesPam = validacionesPam;
		this.activar = activar;
	}
	
	@Override
    public String toString() {
		ObjectMapper mapper = new ObjectMapper();
		String json = null;
		try {
			json = mapper.writeValueAsString(this);
		} catch (JsonProcessingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        return json;
    }
}
