package cl.mp.rgp.common.model;

/**
 * This class was automatically generated by the data modeler tool.
 */
 
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class ValidacionesPam implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String idCampoFront;
	private java.lang.String valorRecibido;
	private java.lang.String mensaje;

	private java.lang.Boolean valido;

	public ValidacionesPam() {
	}

	public java.lang.String getIdCampoFront() {
		return this.idCampoFront;
	}

	public void setIdCampoFront(java.lang.String idCampoFront) {
		this.idCampoFront = idCampoFront;
	}

	public java.lang.String getValorRecibido() {
		return this.valorRecibido;
	}

	public void setValorRecibido(java.lang.String valorRecibido) {
		this.valorRecibido = valorRecibido;
	}

	public java.lang.String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(java.lang.String mensaje) {
		this.mensaje = mensaje;
	}

	public java.lang.Boolean getValido() {
		return this.valido;
	}

	public void setValido(java.lang.Boolean valido) {
		this.valido = valido;
	}

	public ValidacionesPam(java.lang.String idCampoFront,
			java.lang.String valorRecibido, java.lang.String mensaje,
			java.lang.Boolean valido) {
		this.idCampoFront = idCampoFront;
		this.valorRecibido = valorRecibido;
		this.mensaje = mensaje;
		this.valido = valido;
	}
	
    @Override
    public String toString() {
		ObjectMapper mapper = new ObjectMapper();
		String json = null;
		try {
			json = mapper.writeValueAsString(this);
		} catch (JsonProcessingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        return json;
    }

}
